import json

class BoardDef():
    def __init__(self, board):
        
        self.board={"ver"    : 1.0,
                    "board"  : {"name": board, "manufacturer": "vcc-gnd studio"},
                    "mcu"    : {"type": "esp32-c3", "arch": "risc-v", "speed": "80,160"},
                    "eth"    : False,
                    "wifi"   : True,
                    "bt"     : True,
                    "ir"     : False,
                    "rtc"    : False,
                    "temp"   : False,
                    "text"   : "Example file autogenerated, must be fulfilled",
                    "5v0p"  : [],
                    "3v3p"  : [],
                    "gndp"  : [],
                    "enap"  : [],
                    "rstp"  : [],
                    "adc"   : {"adc0": 1, "adc1": 2},
                    "dac"   : {"adc0": 1, "adc1": 2},
                    "pwmp"  : [],
                    "gpio"  : {"gpio0": 2, "gpio1": 3},
                    "ints"  : {"int1": 0, "int2": 0},
                    "i2c"   : [{"scl1": 0, "sda1": 0}],
                    "spi"   : [{"mosi1": 0, "miso1": 0, "cs1": 0, "ck1": 0}],
                    "usart" : [{"tx1": 0, "rx1": 0, "cts1": 0, "rts1": 0}],
                    "i2s"   : [{"clk1": 0, "io1": 0}],
                    "can"   : [{"tx1": 0, "rx1": 0}],
                    "usb"   : [{"D+1": 0, "D-1": 0}],
                    "sdio"  : [{"clk": 0, "cmd": 0, "data0": 0, "data1": 0, "data2": 0, "data3": 0 }],
                    "touch" : {"t1": 0, "t2": 0},
                    "other" : {"vout": 0, "vin": 0, "usrkey": 0, "vref": 0, "flash": 0, "wake": 0, "run": 0, "vbat": 0 },
                    "ncp"   : [],
                    "resvp" : [],
                    "ledp"  : {"gpio2": 12, "gpio3": 13},
                    "rgblp" : {"gpio23": 25}
                    }


    def getBoard(self):
        return self.board
    
    def dumps(self):
        return json.dumps(self.board)
    
    def loads(self, data):
         self.board = json.loads(data)
         
if __name__ == "__main__":      
    b=BoardDef("ESP32C3 module with ESP32C3")

    print("Original")
    print(b.getBoard())

    s=b.dumps()
    print("Codificada")
    print(s)

    b.loads(s)
    print("cargada")
    print(b.getBoard())
